### ISSUE TITLE
When making breaking changes please bump the major version

### ISSUE THREAD

**Issue by krainboltgreene** [wyeworks/boom#83]
Would really appreciate this in the future.

**Comment by iaguirre88** [comment]
Sorry to hear that you might have run into issues.

I agree with you that, in most cases, breaking changes should bump the major version. However, this library is still in the `0.x.x` version, and breaking changes are expected until we reach version `1.x.x.` That's why we try to log every breaking change in the `CHANGELOG.md` file.

This is the guide we are following regarding the version numbers:
https://semver.org/#spec-item-4

If you find any error due to updating Boom, feel free to open an issue and we'll try to help you fix it.
Another solution might be to stick to a specific version so the library won't get automatically updated.

**Comment by krainboltgreene** [comment]
https://semver.org/#spec-item-4
https://semver.org/#spec-item-5
https://semver.org/#how-do-i-know-when-to-release-100

**Comment by iaguirre88** [comment]
We still have some features we'd like to implement that will break the public API and that's why we still not considering Boom as a version 1.

For example:
https://github.com/wyeworks/boom/pull/76
